FROM python:3.7.4
RUN pip install pymongo requests lxml beautifulsoup4 stockquotes


#--
# https://pypi.org/project/pymongo/
# https://pypi.org/project/requests/
# https://pypi.org/project/lxml/
# https://pypi.org/project/beautifulsoup4/
# https://pypi.org/project/stockquotes/
#-- 
